default_model: whisper-small-onnx

models:
  whisper-small-onnx:
    family: stt
    runtime: onnx_whisper
    devices: [cpu, cuda, directml]
    source:
      type: huggingface
      repo_id: onnx-community/whisper-small
      files:
        encoder_model.onnx: onnx/encoder_model.onnx
        decoder_model_merged.onnx: onnx/decoder_model_merged.onnx
        config.json: config.json
        generation_config.json: generation_config.json
        preprocessor_config.json: preprocessor_config.json
        tokenizer.json: tokenizer.json
        tokenizer_config.json: tokenizer_config.json
        special_tokens_map.json: special_tokens_map.json
        vocab.json: vocab.json
        merges.txt: merges.txt
        normalizer.json: normalizer.json
        added_tokens.json: added_tokens.json
    local_path: models/stt/whisper-small-onnx
  whisper-base-en-qnn-snapdragon-x-elite:
    family: stt
    runtime: qnn_whisper
    devices: [qnn]
    decode:
      language: ""
      task: transcribe
      predict_timestamps: false
    source:
      type: url_zip
      url: https://qaihub-public-assets.s3.us-west-2.amazonaws.com/qai-hub-models/models/whisper_base/releases/v0.53.1/whisper_base-precompiled_qnn_onnx-float-qualcomm_snapdragon_x_elite.zip
      required_files_anywhere:
        - encoder.onnx
        - decoder.onnx
    local_path: models/stt/whisper-base-en-qnn-snapdragon-x-elite
