from __future__ import annotations

from pathlib import Path

from backend.app.core.capabilities import HardwareProfile
from scripts import provision


def _profile(arch: str) -> HardwareProfile:
    return HardwareProfile(arch=arch)


def _report_for(profile: HardwareProfile):
    return type("R", (), {"profile": profile, "flags": None})()


def test_dry_run_prints_plan_and_does_not_install(monkeypatch, capsys) -> None:
    monkeypatch.setattr(provision, "_load_profiler", lambda: lambda: _report_for(_profile("amd64")))
    monkeypatch.setattr(
        provision,
        "_run_pip_install",
        lambda command: (_ for _ in ()).throw(AssertionError("install called")),
    )

    exit_code = provision.main(["dry-run"])
    output = capsys.readouterr().out

    assert exit_code == 0
    assert "pip install -e" in output
    assert "hw-x64-base" in output


def test_explain_prints_reasons_for_each_extra(monkeypatch, capsys) -> None:
    monkeypatch.setattr(provision, "_load_profiler", lambda: lambda: _report_for(_profile("arm64")))

    exit_code = provision.main(["explain"])
    output = capsys.readouterr().out

    assert exit_code == 0
    assert "hw-arm64-base" in output
    assert "arch=arm64" in output


def test_install_composes_correct_pip_command_from_resolver(monkeypatch, capsys) -> None:
    monkeypatch.setattr(provision, "_load_profiler", lambda: lambda: _report_for(_profile("amd64")))
    monkeypatch.setattr(provision, "_run_pip_install", lambda command: 0)

    exit_code = provision.main(["install", "--dry-run"])
    output = capsys.readouterr().out

    assert exit_code == 0
    assert provision._build_pip_install_command(["hw-cpu-base", "hw-x64-base", "dev"]) == [
        provision.sys.executable,
        "-m",
        "pip",
        "install",
        "-e",
        ".[hw-cpu-base,hw-x64-base,dev]",
    ]
    assert "pip install -e" in output


def test_lock_emits_requirements_txt_with_generated_marker_comment(
    monkeypatch,
    tmp_path,
    capsys,
) -> None:
    target = tmp_path / "requirements.txt"
    monkeypatch.setattr(provision, "REQUIREMENTS_PATH", target)
    monkeypatch.setattr(provision, "_load_profiler", lambda: lambda: _report_for(_profile("amd64")))
    monkeypatch.setattr(provision, "_read_base_requirements", lambda: ["fastapi>=0.110"])

    exit_code = provision.main(["lock"])
    output = capsys.readouterr().out

    assert exit_code == 0
    assert target.exists()
    assert target.read_text(encoding="utf-8").startswith("# Generated by scripts/provision.py lock")
    assert "fastapi>=0.110" in target.read_text(encoding="utf-8")
    assert "wrote" in output


def test_verify_reports_drift_when_installed_set_differs(monkeypatch, capsys) -> None:
    monkeypatch.setattr(provision, "_load_profiler", lambda: lambda: _report_for(_profile("amd64")))
    monkeypatch.setattr(provision, "_installed_distribution_names", lambda: {"fastapi", "uvicorn"})

    exit_code = provision.main(["verify"])
    output = capsys.readouterr().out

    assert exit_code == 1
    assert "missing" in output
