from __future__ import annotations

import argparse
import importlib.metadata
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from backend.app.core.logging import configure_logging, emit_host_fingerprint
from backend.app.core.paths import REPO_ROOT as APP_REPO_ROOT
from backend.app.core.capabilities import HardwareProfile
from backend.app.hardware.provisioning import (
    explain_required_extras,
    resolve_required_extras,
    resolve_required_requirement_names,
)


REQUIREMENTS_PATH = APP_REPO_ROOT / "backend" / "requirements.txt"


def _load_profiler():
    from backend.app.hardware.profiler import run_profiler

    return run_profiler


def _current_timestamp() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _read_base_requirements() -> list[str]:
    try:
        import tomllib
    except ImportError:  # pragma: no cover - Python 3.11 always has tomllib
        return []

    pyproject_path = APP_REPO_ROOT / "pyproject.toml"
    data = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))
    dependencies = data.get("project", {}).get("dependencies", [])
    return [str(item).strip() for item in dependencies if str(item).strip()]


def _installed_distribution_names() -> set[str]:
    names: set[str] = set()
    for distribution in importlib.metadata.distributions():
        metadata = distribution.metadata
        name = metadata.get("Name")
        if name:
            names.add(str(name).strip().lower())
    return names


def _normalize_requirement_name(requirement: str) -> str:
    candidate = requirement.split(";", 1)[0].strip()
    if "[" in candidate:
        candidate = candidate.split("[", 1)[0]
    for separator in ("<", ">", "=", "!", " "):
        if separator in candidate:
            candidate = candidate.split(separator, 1)[0]
    return candidate.strip().lower()


def _build_pip_install_command(extras: list[str], include_porcupine: bool = False) -> list[str]:
    resolved_extras = list(extras)
    if include_porcupine and "hw-wake-porcupine" not in resolved_extras:
        resolved_extras.insert(-1, "hw-wake-porcupine")
    extras_spec = ",".join(resolved_extras)
    return [sys.executable, "-m", "pip", "install", "-e", f".[{extras_spec}]"]


def _write_requirements_lockfile(path: Path | None = None) -> None:
    if path is None:
        path = REQUIREMENTS_PATH
    lines = [
        f"# Generated by scripts/provision.py lock at {_current_timestamp()}",
        "# Base extra only. Do not edit by hand.",
        "",
    ]
    lines.extend(_read_base_requirements())
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _emit_plan(
    profile: HardwareProfile,
    extras: list[str],
    include_porcupine: bool,
    out=None,
) -> None:
    if out is None:
        out = sys.stdout
    emit_host_fingerprint(profile, extras, out=out)
    for extra, reason in explain_required_extras(profile, include_porcupine):
        print(f"{extra}: {reason}", file=out)


def _run_pip_install(command: list[str]) -> int:
    completed = subprocess.run(command, check=False)
    return completed.returncode


def _parse_args(argv: list[str]) -> argparse.Namespace:
    shared = argparse.ArgumentParser(add_help=False)
    shared.add_argument("--verbose", action="store_true")
    shared.add_argument("--dry-run", action="store_true")
    shared.add_argument("--trace-to")
    shared.add_argument("--profile", action="store_true")

    parser = argparse.ArgumentParser(prog="provision.py", parents=[shared])
    subparsers = parser.add_subparsers(dest="command", required=True)

    install = subparsers.add_parser("install", parents=[shared])
    install.add_argument("--with-porcupine", action="store_true")

    verify = subparsers.add_parser("verify", parents=[shared])
    verify.add_argument("--with-porcupine", action="store_true")

    dry_run = subparsers.add_parser("dry-run", parents=[shared])
    dry_run.add_argument("--with-porcupine", action="store_true")

    explain = subparsers.add_parser("explain", parents=[shared])
    explain.add_argument("--with-porcupine", action="store_true")

    subparsers.add_parser("lock", parents=[shared])
    return parser.parse_args(argv)


def _provision_context(include_porcupine: bool) -> tuple[HardwareProfile, list[str]]:
    profiler = _load_profiler()
    report = profiler()
    extras = resolve_required_extras(report.profile, include_porcupine=include_porcupine)
    return report.profile, extras


def _expected_distribution_names(profile: HardwareProfile, include_porcupine: bool) -> set[str]:
    expected = {
        _normalize_requirement_name(requirement)
        for requirement in _read_base_requirements()
        if _normalize_requirement_name(requirement)
    }
    expected.update(
        resolve_required_requirement_names(profile, include_porcupine=include_porcupine)
    )
    return expected


def _run_install(profile: HardwareProfile, extras: list[str], include_porcupine: bool) -> int:
    command = _build_pip_install_command(extras, include_porcupine=include_porcupine)
    return _run_pip_install(command)


def _run_verify(profile: HardwareProfile, extras: list[str], include_porcupine: bool) -> int:
    expected_requirements = _expected_distribution_names(
        profile,
        include_porcupine=include_porcupine,
    )
    installed_requirements = _installed_distribution_names()
    missing = sorted(expected_requirements - installed_requirements)
    unexpected = sorted(installed_requirements & expected_requirements)
    print(f"expected_requirements={sorted(expected_requirements)}")
    print(f"installed_requirements={sorted(installed_requirements)}")
    if missing:
        print(f"missing={missing}")
    if unexpected:
        print(f"present={unexpected}")
    return 0 if not missing else 1


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv or sys.argv[1:])
    configure_logging(level="DEBUG" if args.verbose else "INFO", trace_to=args.trace_to)

    if args.command == "lock":
        profile, extras = _provision_context(include_porcupine=False)
        emit_host_fingerprint(profile, extras)
        _write_requirements_lockfile()
        print(f"wrote {REQUIREMENTS_PATH}")
        return 0

    include_porcupine = bool(getattr(args, "with_porcupine", False))
    profile, extras = _provision_context(include_porcupine=include_porcupine)
    emit_host_fingerprint(profile, extras, readiness="not-checked")

    if args.command == "explain":
        for extra, reason in explain_required_extras(profile, include_porcupine=include_porcupine):
            print(f"{extra}: {reason}")
        return 0

    if args.command == "dry-run":
        command = _build_pip_install_command(extras, include_porcupine=include_porcupine)
        print(" ".join(command))
        for extra, reason in explain_required_extras(profile, include_porcupine=include_porcupine):
            print(f"{extra}: {reason}")
        return 0

    if args.command == "verify":
        return _run_verify(profile, extras, include_porcupine=include_porcupine)

    if args.command == "install":
        command = _build_pip_install_command(extras, include_porcupine=include_porcupine)
        print(" ".join(command))
        if args.dry_run:
            return 0
        return _run_install(profile, extras, include_porcupine=include_porcupine)

    raise ValueError(f"unsupported command: {args.command}")


if __name__ == "__main__":
    raise SystemExit(main())
